/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yava.tester;

import java.util.List;

import io.getunleash.DefaultUnleash;
import io.getunleash.EvaluatedToggle;
import io.getunleash.Unleash;
import io.getunleash.UnleashContext;
import io.getunleash.util.UnleashConfig;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public boolean setupUnleash() {
        UnleashConfig config = UnleashConfig.builder()
                .unleashAPI("http://localhost:4242/api")
                .appName("some-app-name2")
                .apiKey("*:development.0b07154943ac073d7ea776b75ea89124e0af9c48946db3b8265e87e4")
                .instanceId("some-instance-id")
                .synchronousFetchOnInitialisation(true)
                .build();

        Unleash unleash = new DefaultUnleash(config);

        while (true) {
            try {
                Thread.sleep(10000);
                UnleashContext context = UnleashContext.builder().appName("2.5.5")
                        .addProperty("brand", "ANDROID").build();
                List<EvaluatedToggle> toggles = unleash.more().evaluateAllToggles(context);
                // boolean enabled = unleash.isEnabled("cousin", context);
                Thread.sleep(5000);
                return true;
            } catch (Exception ex) {
                throw new RuntimeException("Something went wrong");
            }
        }
    }
}
