/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yava.tester;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

import io.getunleash.DefaultUnleash;
import io.getunleash.EvaluatedToggle;
import io.getunleash.Unleash;
import io.getunleash.UnleashContext;
import io.getunleash.util.UnleashConfig;

class AppTest {
        @Test
        void unleashDoesAsExpected() {
                UnleashConfig config = UnleashConfig.builder()
                                .unleashAPI("http://localhost:4242/api")
                                .appName("test-application")
                                .apiKey("*:development.0b07154943ac073d7ea776b75ea89124e0af9c48946db3b8265e87e4")
                                .synchronousFetchOnInitialisation(true)
                                .sendMetricsInterval(5)
                                .build();

                Unleash unleash = new DefaultUnleash(config);

                UnleashContext context = UnleashContext.builder()
                                .environment("production")
                                .build();

                List<EvaluatedToggle> toggles = unleash.more().evaluateAllToggles(context);
                System.out.println("Got me some toggles!");
                toggles.forEach(toggle -> {
                        System.out.println(toggle.getName() + " is " + toggle.isEnabled());
                });

                System.out.println("Forced control eval of control: " + unleash.isEnabled("control", context));

                try {
                        Thread.sleep(10000);
                } catch (Exception e) {
                        throw new RuntimeException(e);
                }
                System.out.println("Done sleeping!");
                assertTrue(false);
                // assertTrue(unleash.isEnabled("pwrview.home-aggregation.enable", context),
                // "It should be enabled");

        }
}
